### ISSUE TITLE
use openDB , but getRange  can see the other db's data

### ISSUE THREAD

**Issue by gcxfd** [DoctorEvidence/lmdb-store#11]
![image](https://user-images.githubusercontent.com/69608605/92087912-ba391280-edfe-11ea-9740-9e5c3bfebc5e.png)

**Comment by kriszyp** [comment]
Would you mind pasting in some of the code you used for this (so I don't have to try to type it in from the screenshot)?

**Comment by gcxfd** [comment]
i resolved , pass name for openDB then ok

**Comment by kriszyp** [comment]
Ah, i see, missing the name, I should have caught that. Maybe I can add some error handling for that.
