### ISSUE TITLE
Unexpected "Resizing database X to Y" console messages

### ISSUE THREAD

**Issue by spalger** [DoctorEvidence/lmdb-store#12]
I've only been trying out lmdb-store for a couple hours, but I'm loving it so far!

I'd like to better understand what I should know about the `Resizing database X to Y` messages being logged to console. I'm not surprised this is happening as we're storing a decent amount of data in the database but I'd much rather not see these messages if there isn't anything I'm supposed to do about them.

**Comment by kriszyp** [comment]
Removed logging of resizing in 0.6.10. Thank you!
