### ISSUE TITLE
MDB_READERS_FULL: raising max readers

### ISSUE THREAD

**Issue by spalger** [DoctorEvidence/lmdb-store#14]
We sometimes run our codebase that uses lmdb-store in pretty massive parallelization to search for flaky tests, and after integrating lmdb-store we're seeing `MDB_READERS_FULL` errors getting logged and the process exiting. I don't see anything in the docs about the `maxReaders` option that `node-lmdb` seems to support, is there a reason it's not documented? Should we not use it? What kind of considerations should we keep in mind when raising this value?

**Comment by kriszyp** [comment]
I believe it should be fine to increase the number of readers, and I can certainly add that to the documentation. This is in the information provided in the LMDB docs:
http://www.lmdb.tech/doc/group__mdb.html#gae687966c24b790630be2a41573fe40e2
I have only run MDB_READERS_FULL errors when we have some type of error that causes excessive spawning of processes, but if you are intentionally creating a lot of processes, it seems reasonable to adjust the max readers accordingly.
