### ISSUE TITLE
getRange options have the wrong typescript fields

### ISSUE THREAD

**Issue by josephg** [DoctorEvidence/lmdb-store#16]
The db.getRange(options) method uses options.limit, options.values and options.versions fields. None of these are present in the corresponding [typescript type for RangeOptions](https://github.com/DoctorEvidence/lmdb-store/blob/27800650c81d3b7c2f9e21838920e39a4144aa2c/index.d.ts#L56-L62):

```
	interface RangeOptions {
		start?: Key
		end?: Key
		reverse?: boolean
		includeValues?: boolean // Should be values?: boolean
		includeVersions?: boolean // should be versions?: boolean
		// Missing: limit?: number
	}
```

**Comment by kriszyp** [comment]
Thanks for the tip! Fixed in 0.8.8.

**Comment by kriszyp** [comment]
Also, I fixed the referenced weak-lru-cache version so it shouldn't cause loading issues in 0.8.8 as well.

**Comment by josephg** [comment]
Awesome - much appreciated! So fast!
