### ISSUE TITLE
Publish releases?

### ISSUE THREAD

**Issue by spalger** [DoctorEvidence/lmdb-store#17]
I'm looking to upgrade from version 6.10 to latest and feel the need to step through the commit log since there isn't any changelog. Additionally, it would be great to be notified of releases as the happen.

Pushing tags and defining some release info for each release would knock out two birds with one stone, or I'd be happy to start a changelog if you'd like to go that route. Thoughts?

**Comment by kriszyp** [comment]
Yes, that sounds like a great idea, I can create releases with notes, at least for significant releases. And FYI, if you are upgrading, probably the most significant thing to be aware of is the LMDB itself has upgraded the DB format (and the format is incompatible with older versions), so I have included code that should automatically upgrade any older database that is opened to the newer format.

**Comment by spalger** [comment]
Thanks!
