### ISSUE TITLE
Getting error when installing lmdb-store

### ISSUE THREAD

**Issue by SethiShivam** [DoctorEvidence/lmdb-store#2]
Hi Doctorr ,
I hope you are doing good . I am trying to install lmdb-store library but i am getting error 
/src/env.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE EnvWrap::detachBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/env.cpp:528:44: error: ‘class v8::ArrayBuffer’ has no member named ‘Detach’; did you mean ‘Data’?
     Local<v8::ArrayBuffer>::Cast(info[0])->Detach();
                                            ^~~~~~
                                            Data
../src/env.cpp: In static member function ‘static void EnvWrap::setupExports(v8::Local<v8::Object>)’:
../src/env.cpp:828:148: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’, declared with attribute warn_unused_result [-Wunused-result]
 ocalChecked(), envTpl->GetFunction(Nan::GetCurrentContext()).ToLocalChecked());
                                                                              ^
In file included from ../src/node-lmdb.h:29:0,
                 from ../src/env.cpp:24:

I have tried it using multiple node versions .
NODE : 8.17.0
NODE : 10.20

**Comment by kriszyp** [comment]
This should be fixed with https://github.com/DoctorEvidence/lmdb-store/commit/15402b74b73703360ba79ade1b2f10c515e3ddb0, let me know if you have any issues.
