### ISSUE TITLE
Feature request for range searches, add an offset attribute

### ISSUE THREAD

**Issue by kylebernhardy** [DoctorEvidence/lmdb-store#33]
Hi,

I was wondering if an offset option could be added to range searches.  This would allow for pagination in conjunction with the limit attribute.  An example would be getting the first 1000 entries, then the next 1000 entries:

```
for(const {key, value} of store.getRange({limit: 1000})){
    ....
}
```

```
for(const {key, value} of store.getRange({offset:1000, limit: 1000})){
    ....
}
```

Or does something like this already exist?

**Comment by kriszyp** [comment]
It does not exist yet, but it is a very good idea. Will look into adding it.

**Comment by kriszyp** [comment]
Published v1.0.1, let me know if you see anything missing there.

**Comment by kylebernhardy** [comment]
Thank you, I am working on wiring this feature into our product today.  I'll keep this thread open in case any issues emerge.

**Comment by kylebernhardy** [comment]
Confirming all worked well.  Closing request.
