### ISSUE TITLE
Is there a way to check if a key/value pair entry exists?

### ISSUE THREAD

**Issue by kylebernhardy** [DoctorEvidence/lmdb-store#39]
Specifically I'm wondering if there is an equivalent for goToDup from node-lmdb.

Thanks!

**Comment by kriszyp** [comment]
No, there is currently no equivalent (although you could look through all the values returned by getValues(key), but that isn't very efficient). A couple of options (maybe both would be worthwhile):

- Add startValue and endValue options to getValues so you could specifically search for a range of values for a given key.
- Add a direct method to check for the existence of a key/value (maybe `doesExist(key, value)`).

**Comment by kylebernhardy** [comment]
I like the doesExist option, that feels pretty clean to me.

**Comment by kylebernhardy** [comment]
This works greta, the only thing I found is if a key value on a dupsorted key is false on a key/value pairing that exists then the returned result is false.  Here is a sample:

```

const fs = require('fs');
const path = require('path');
const lmdb = require('lmdb-store');
const assert = require('assert');

function createEnv(name){
    let environment_path = path.join(__dirname, 'data', name);
    try {
        fs.rmdirSync(environment_path, {recursive:true})
        fs.mkdirSync(environment_path);
    }catch(e){
        console.error(e);
    }
    let env_init = {
        "path": environment_path,
        "mapSize": 1024*1024,
        "maxReaders": 100
    };
    let env = lmdb.open(env_init);
    return env;
}

let env = createEnv('test');

let bool_dbi = env.openDB('bool', {
    create: true,
    dupSort: true,
    useVersions: false});

bool_dbi.putSync(true, 1);
bool_dbi.putSync(true, 5);
bool_dbi.putSync(true, 2);
bool_dbi.putSync(false, 3);
bool_dbi.putSync(false, 4);
bool_dbi.putSync(false, 6);

assert.deepStrictEqual(bool_dbi.doesExist(true,3), false);
assert.deepStrictEqual(bool_dbi.doesExist(true,5), true);
assert.deepStrictEqual(bool_dbi.doesExist(false), true);

assert.deepStrictEqual(bool_dbi.doesExist(false,3), true); //this line fails
```
