### ISSUE TITLE
Expose MDB_APPEND

### ISSUE THREAD

**Issue by vladar** [DoctorEvidence/lmdb-store#43]
I am curious about your thoughts on `MDB_APPEND` flag? It should be useful when storing sequential data in LMDB. It is even listed in Wikipedia [page about LMDB](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database) as one of the main advantages 🙂

As far as I understand there is no way to use it with `lmdb-store`. Is it an intentional decision or just not implemented yet?

**Comment by kriszyp** [comment]
This simply has not been implemented yet, but I think adding support for this seems like a worthwhile addition. I'll take a look at getting this in.

**Comment by kriszyp** [comment]
Currently there is support for this in putSync, and I have update the docs and types to indicate how to use this. Adding support for this async put will be a little more involved. Also, a caveat that these flags are currently implemented through properties in an options objects and a standard (without MDB_APPEND) is so fast, that it is possible that checking the properties of an object may add enough extra overhead that using append might not be faster.

**Comment by vladar** [comment]
Thanks!

**Comment by kriszyp** [comment]
FWIW, I do still plan on implementing a faster version of this.
