### ISSUE TITLE
Incorrect typings with transactionAsync

### ISSUE THREAD

**Issue by paul-go** [DoctorEvidence/lmdb-store#50]
The type definition is:
`transactionAsync<T>(action: () => T): T`

But it should be:
`transactionAsync<T>(action: () => T): Promise<T>`

By the way, thank you for the recent addition of async transactions. I know many times in open source, especially with less popular projects, these thoughts "Is anyone going to care?" are common. Well, this feature just got me out of a really tight spot in a mission-critical project.

**Comment by kriszyp** [comment]
Should be fixed in v1.5.3.
