### ISSUE TITLE
SIGSEGV on open()

### ISSUE THREAD

**Issue by 1N50MN14** [DoctorEvidence/lmdb-store#57]
For some reason `open()` throws SIGSEGV when running in a container, or at least in my container, based off node-alpine-14.7 (dockerfile here https://gist.github.com/1N50MN14/4b4a2944807022e2bc4b292ac97daeef). There's more than enough CPU and memory allocated as well as storage (persistent SSD).

Problem is the only log that I can see is the SIGENV process exit itself, any tips on how I can trace down the issue or get some sort of output logs?

EDIT: It happens with/without shared structures enabled, new/existing data.. 

Many thanks

(PS: So wonderful to see lmdb-store growing!)

**Comment by kriszyp** [comment]
I am really not sure trace the segmentation fault itself. I assume this is a unix flavor, and not using any of the prebuilds (which I thought was more likely to have debugging symbols, but not sure). Are you interested in having more logging in to the `open()` method to see exactly when the error occurs?

**Comment by 1N50MN14** [comment]
You were right in your assumption, it was the unix flavor, I switched over to buster slim and it worked as expected... I'm ok with that. Yeah I think it's a good idea to have some sort of logging if you have the time for it and if possible at all I guess this one is tricky... 

Many thanks again, closing this issue for now
