### ISSUE TITLE
Can the files generated be read by other language?

### ISSUE THREAD

**Issue by eramirez51** [DoctorEvidence/lmdb-store#61]
This is just a question. LMDB is a portable format. Can the files generated by lmdb-store, be read by Golang(for example) using standard LMDB library? Thank you for your answer.

**Comment by kriszyp** [comment]
Yes, but there are certainly some caveats, or things that can cause incompatibility:
- lmdb-store uses the latest version of LMDB from the mdb.master3 branch, which is incompatible with earlier LMDB in the 0.9.x line, that are probably still more commonly used in many packages (the newest format has an extra header in the db pages). This is likely to be the biggest issue.
- Naturally if you are storing structured data with one of the lmdb-store serializers, you would need to use the same format to deserialize. And if you are using JSON, would need to ensure it is read/written with UTF-8 encoding.
- I believe LMDB also stores many internal integers with the local machine's natural endian. So, technically you can't take the format from a big-endian to a little-endian computer, but big-endian is so rare these days, I doubt that would be a problem.

**Comment by eramirez51** [comment]
Thanks for the answer. Closing.
