### ISSUE TITLE
use zstd compress dict for lz4 ?

### ISSUE THREAD

**Issue by gcxfd** [DoctorEvidence/lmdb-store#9]
i saw the readme.md write

lmdb-store can optionally use off-thread LZ4 compression ..... Zstandard provides utilities for creating your own optimized shared dictionary

![image](https://user-images.githubusercontent.com/69608605/92071218-c1512800-ede0-11ea-9c7e-7b90c32f5e7e.png)

**Comment by kriszyp** [comment]
Is the issue here about getting more information about ZStandard (https://facebook.github.io/zstd/)?

**Comment by gcxfd** [comment]
i found the how to

https://github.com/lz4/lz4/releases/tag/v1.8.1.2

```
lz4 doesn't specify how to build a dictionary. All it says is that it can be any file up to 64 KB.
This approach is compatible with zstd dictionary builder, which can be instructed to create a 64 KB dictionary with this command :

zstd --train dirSamples/* -o dictName --maxdict=64KB

```
