### ISSUE TITLE
lmdb-store vs lmdb docs

### ISSUE THREAD

**Issue by cekvenich2** [DoctorEvidence/lmdb-store#94]
Docs say require('lmdb'), but need to say require('lmdb-store')

In general there is confusion with the packages. One should be marked as deprecated.

**Comment by kriszyp** [comment]
If I were to rename the repository, it might be reasonable to simply call it `lmdb-js`. With eventually publishing to Deno (and maybe someday adding WASM support), it will be more generally the JS LMDB adapter.

**Comment by cekvenich2** [comment]
The name does not matter IMO, what is important that there be one working npm for us to use. Just tell us what one. 
If you do create a 3rd name, just edit readme on two older npm saying that these are deprecated and to use the 3rd one.

**Comment by kriszyp** [comment]
Sounds good. I was just curious if anyone had feedback on this. But there won't be any third name (mentioned `lmdb-js` as a possible repository name, but _not_ npm package name). The npm package name to use is `lmdb` and will be `lmdb` going forward (just as the docs indicate with `npm install lmdb`). I will make this more clear in the docs and versions going forward in v2.0.

**Comment by cekvenich2** [comment]
IMO it is OK to have 2 git repo and 2 npm names: as long as the deprecated/legacy ones says so, and it points to the current one.

**Comment by vladar** [comment]
I agree that moving to a single package name `lmdb` for 2.0 makes sense, however, I would expect `lmdb-store` to be still available for `1.x` release line, including future maintenance releases (if ever needed).

**Comment by kriszyp** [comment]
> I would expect lmdb-store to be still available for 1.x release line, including future maintenance releases (if ever needed).

Yes, absolutely, lmdb-store@1.x will continue to exist and be maintained (and not deprecated anytime soon).
